#!/bin/bash

if [ "$1" = "" ]
then
    echo dbgc: error: no arguments provided
    echo usage: dbgc file.c [argv]
    exit 1
fi

if ! [[ "$1" == *".c" ]]
then
    echo dbgcpp: error: file should have '.c' extension
    exit 2
fi

base=$(basename -s .c $1)

gcc -Wall -lm -g -ggdb -D DEBUG="(1)" -o ./$base $1

if ! [ "$?" -eq "0" ]
then
    exit "$?"
fi

mkdir -p ~/.tmp/dbgc/
mv ./$base ~/.tmp/dbgc/$base
chmod +x ~/.tmp/dbgc/$base

echo debug: $1
gdb ~/.tmp/dbgc/$base

rm ~/.tmp/dbgc/$base
