#!/bin/bash

if [ "$1" = "" ]
then
    echo dbgc: error: no arguments provided
    echo usage: dbgc file.c [argv]
    exit 1
fi

base=$(basename -s .c $1)

echo debug: $1

gcc -Wall -lm -g -ggdb -D DEBUG="(1)" -o ./$base $1

if ! [ "$?" = "0" ]
then
    exit "$?"
fi

mkdir -p ~/.tmp/dbgc/
mv ./$base ~/.tmp/dbgc/$base
chmod +x ~/.tmp/dbgc/$base

gdb ~/.tmp/dbgc/$base

rm ~/.tmp/dbgc/$base
