#!/bin/bash

if [ "$1" = "" ]
then
    echo runc: error: no arguments provided
    exit 1
fi

base=$(basename -s .c $1)

echo run: $1

gcc -Wall -o ./$base $1

if ! [ "$?" = "0" ]
then
    exit "$?"
fi

./$base
rm ./$base
