#!/bin/bash

if [ "$1" = "" ]
then
    echo runc: error: no arguments provided
    echo usage: runc file.c [argv]
    exit 1
fi

if ! [[ "$1" == *".c" ]]
then
    echo dbgcpp: error: file should have '.c' extension
    exit 2
fi

base=$(basename -s .c $1)

gcc -Wall -lm -o ./$base $1

if ! [ "$?" -eq "0" ]
then
    exit "$?"
fi

mkdir -p ~/.tmp/runc/
mv ./$base ~/.tmp/runc/$base
chmod +x ~/.tmp/runc/$base

echo run: $1
~/.tmp/runc/$base "${@:2}"
retval=$?

rm ~/.tmp/runc/$base
exit $retval
